// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZV8H1HOKfvnYUvAyY18-9Dtg8hqjV0Tg',
    appId: '1:448982496080:web:a0345c2e5ea91f85ccf255',
    messagingSenderId: '448982496080',
    projectId: 'smithfirestore1749',
    authDomain: 'smithfirestore1749.firebaseapp.com',
    storageBucket: 'smithfirestore1749.appspot.com',
    measurementId: 'G-BVPPCWGYZ0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASDJP551r4THWPaaQs4K9ftI9c4Ep_TqI',
    appId: '1:448982496080:android:b33160ad73ce5d36ccf255',
    messagingSenderId: '448982496080',
    projectId: 'smithfirestore1749',
    storageBucket: 'smithfirestore1749.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDA9uhZ2o8d15qgpR3CEHNilz7iIpRulcc',
    appId: '1:448982496080:ios:9ff68f5e927f9607ccf255',
    messagingSenderId: '448982496080',
    projectId: 'smithfirestore1749',
    storageBucket: 'smithfirestore1749.appspot.com',
    iosClientId: '448982496080-o0vp30manivjct38en748f58uqm3kbba.apps.googleusercontent.com',
    iosBundleId: 'hello.com.notes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDA9uhZ2o8d15qgpR3CEHNilz7iIpRulcc',
    appId: '1:448982496080:ios:9ff68f5e927f9607ccf255',
    messagingSenderId: '448982496080',
    projectId: 'smithfirestore1749',
    storageBucket: 'smithfirestore1749.appspot.com',
    iosClientId: '448982496080-o0vp30manivjct38en748f58uqm3kbba.apps.googleusercontent.com',
    iosBundleId: 'hello.com.notes',
  );
}
